backend:
  name: git-gateway

  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: onebitrocket/11ty.northerndorsetbreedersclub.co.uk

local_backend: true

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "_src/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads"

collections:
  # blog posts
  - name: "blogposts"
    label: "Blog posts"
    labelSingular: "Blog post"
    description: >
      Add your blog posts in here.
    folder: "_src/blog"
    create: true
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    slug: "{{slug}}"
    fields:
      - label: "SEO settings"
        name: "meta"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string", required: false, hint: "The page title visible in google search results" }
          - { label: "Description", name: "desc", widget: "string", required: false, hint: "The description title visible in google search results" }
      - { label: "Title", name: "title", widget: "string", hint: "The title of the post" }
      - { label: "Summary", name: "summary", widget: "text", required: false, hint: "A short description that appears on the blog listing pages" }
      - { label: "Featured Image", name: "featured_img", widget: "image", required: false, hint: "The thumbnail image that appears on the  blog listing page" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false, editorComponents: [ "image", "file" ], buttons: [  "bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list" ] }
  # EVENTS posts
  - name: "eventposts"
    label: "Events"
    labelSingular: "Event"
    description: >
      Add your event items in here.

      Past events will automatcially hide be remove from the site.
    folder: "_src/events"
    create: true
    slug: "{{slug}}"
    summary: '{{title}} -- {{startDate}}'
    fields:
      - label: "SEO settings"
        name: "meta"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string", required: false, hint: "The page title visible in google search results" }
          - { label: "Description", name: "desc", widget: "string", required: false, hint: "The description title visible in google search results" }
      - { label: "Title", name: "title", widget: "string", hint: "The title of the post" }
      - { label: "Summary", name: "summary", widget: "text", required: false, hint: "A short description that appears on the event listing pages" }
      - { label: "Featured Image", name: "featured_img", widget: "image", required: false, hint: "The thumbnail image that appears on the event listing page" }
      - { label: "Start Date", name: "startDate", widget: "datetime", required: false }
      - { label: "End Date", name: "endDate", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false, editorComponents: [ "image", "file" ], buttons: [  "bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list" ] }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Map link", name: "map", widget: "string", required: false }
      - { label: "All day event", name: "allDay", widget: "boolean", required: false}
  # PAGES
  - name: "pages"
    label: "Pages"
    labelSingular: "Page"
    folder: "_src"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "SEO settings"
        name: "meta"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "desc", widget: "string", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "desc", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "config"
    label: "Admin"
    description: "Administer site settings"
    create: false
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "config"
        file: "_src/_data/config.json"
        widget: "object"
        fields:
          - { label: "Site title", name: "title", widget: "string" }
          - { label: "Site description", name: "desc", widget: "string" }
          - { label: "Site url", name: "url", widget: "hidden" }
          - label: "Contact details"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Contact Number", name: "phone", widget: "string", required: false }
              - { label: "Contact Email", name: "email", widget: "string", required: false }
              - { label: "Facebook page", name: "facebook", widget: "string", required: false }
              - label: "Address"
                name: "address"
                widget: "object"
                fields:
                - { label: "Name", name: "name", widget: "string", required: false }
                - { label: "Building name", name: "building", widget: "string", required: false }
                - { label: "Street", name: "street", widget: "string", required: false }
                - { label: "City", name: "city", widget: "string", required: false }
                - { label: "County", name: "county", widget: "string", required: false }
                - { label: "Postcode", name: "postcode", widget: "string" , required: false}

