backend:
  # name: test-repo
  name: git-gateway

local_backend: true

  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: onebitrocket/11ty.northerndorsetbreedersclub.co.uk

  branch: development
  # branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "uploads" # Media files will be stored in the repo under images/uploads

collections:
  # Projects
  - name: "blogposts" # Used in routes, e.g., /admin/collections/projects
    label: "Blog posts" # Used in the UI
    labelSingular: "Blog posts"
    folder: "_src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "desc", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

